<a href="https://colab.research.google.com/github/sitbayevalibek/numpy_transpose_swapaxes/blob/main/transpose_swapaxes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Transpose va swapaxes xususiyatlariga kichik misol.

In [1]:
import numpy as np

In [2]:
t_s = np.arange(6).reshape(3, 2)
t_s

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
t_s

array([[0, 1],
       [2, 3],
       [4, 5]])

Transpose 

In [4]:
t_s.T

array([[0, 2, 4],
       [1, 3, 5]])

In [5]:
t_s

array([[0, 1],
       [2, 3],
       [4, 5]])

Swapaxes

In [6]:
t_s.swapaxes

<function ndarray.swapaxes>

In [7]:
t_s.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [10]:
t_s

array([[0, 1],
       [2, 3],
       [4, 5]])

Matritsalarni bir-birga ko'paytirish (t_s * t_s.T)
     
    ".dot()" orqali

In [11]:
t_s.dot(t_s.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])